name: Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps: 

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        fetch-depth: 0

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build
      run: ./deploy/increment.sh -v patch

    - name: Build
      run: ./deploy/build.sh

    - name: Push
      run: ./deploy/push.sh